import Auth from "../utils/auth";
import { getUserIdFromToken } from "../utils/userToken";

const createInteraction = async (interactionType: string, catId: number) => {
  console.log(`Interaction: ${interactionType}`); // Debugging

  try {
    console.log("cat id is", catId); // debugging
    const response = await fetch(`api/interactions/${catId}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${Auth.getToken()}`,
      },
      body: JSON.stringify({
        userId: getUserIdFromToken,
        catId,
        interactionType, // Play, Feed, or Gift
        description:
          interactionType === "play"
            ? `Owner ${interactionType}s with the cat.`
            : interactionType === "feed"
            ? `Owner ${interactionType}s the cat.`
            : `Owner gives the cat a ${interactionType}!`,
        // date and id would be auto-generated by the server
      }),
    });

    if (!response.ok) {
      throw new Error(`HTTP error! Status: ${response.status}`);
    }

    const data = await response.json();
    console.log("Interaction response from interactionAPI:", data);
    return data;
  } catch (error) {
    console.error("Error handling interaction:", error);
  }
};

// retrieve last 5 interactions
const retrieveLast5Interactions = async (catId: number, userId: number) => {
  try {
    const response = await fetch(
      `/api/interactions/lastfive/cats?catId=${catId}&userId=${userId}`,
      {
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${Auth.getToken()}`,
        },
      }
    );
    if (!response.ok) {
      throw new Error(`HTTP error! Status: ${response.status}`);
    }

    const data = response.json();
    console.log("last five interactions are", data);
    return data;
  } catch (error) {
    console.log("Error retrieving last five interactions", error);
  }
};

export { createInteraction, retrieveLast5Interactions };
