import Auth from "../utils/auth";
import { getUserIdFromToken } from "../utils/userToken";

const createInteraction = async (interactionType: string, catId: number) => {
  console.log(`Interaction: ${interactionType}`); // Debugging

  try {
    console.log("cat id is", catId); // debugging
    const response = await fetch(`api/interactions/${catId}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${Auth.getToken()}`,
      },
      body: JSON.stringify({
        userId: getUserIdFromToken,
        catId,
        interactionType, // Play, Feed, or Gift
        description: "User /played/ with the cat",
        // date and id would be auto-generated by the server
      }),
    });

    if (!response.ok) {
      throw new Error(`HTTP error! Status: ${response.status}`);
    }

    const data = await response.json();
    console.log("Interaction response from interactionAPI:", data);
    return data;
  } catch (error) {
    console.error("Error handling interaction:", error);
  }
};

export { createInteraction };

// get last 5 interactions of that catId and that userId

// get the user Id and cat Id with their last 5 interactions.
// when you do gift the yarn should drop
