// Cats are not adopted initially so userId is null until adopted by a user
const cats = [
  {
    name: "Whiskers",
    avatar: "./assets/cats/cat-01/chat-01.png",
    skin: "orange",
    personality: "curious/funny",
    mood: 5,
    patience: 10,
    lastFeedDate: null,
    deathFlag: 7,
    isAlive: true,
    userId: null,
  },
  {
    name: "Bubbles",
    avatar: "./assets/cats/cat-02/chat-01.png",
    skin: "light brown",
    personality: "excited/bubbly",
    mood: 5,
    patience: 10,
    lastFeedDate: null,
    deathFlag: 7,
    isAlive: true,
    userId: null,
  },
  {
    name: "Shadow",
    avatar: "./assets/cats/cat-03/chat-01.png",
    skin: "black",
    personality: "quiet/mysterious",
    mood: 5,
    patience: 10,
    lastFeedDate: null,
    deathFlag: 7,
    isAlive: true,
    userId: null,
  },
  {
    name: "Mittens",
    avatar: "./assets/cats/cat-04/chat-01.png",
    skin: "brown",
    personality: "affectionate/easygoing",
    mood: 5,
    patience: 10,
    lastFeedDate: null,
    deathFlag: 7,
    isAlive: true,
    userId: null,
  },
];

export default cats;
